apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-install-customization
spec:
  profile: demo
  hub: docker.io/istio
  tag: 1.13.1
  revision: 1-13-1
  namespace: istio-system
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: "REGISTRY_ONLY"
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 7
          minReplicas: 1
        nodeSelector:
          beta.kubernetes.io/os: linux
    # ingressGateways:
    # - name: istio-ingressgateway
    #   #namespace: istio-ingress
    #   enabled: true
    #   label:
    #     istio: ingressgateway
    #   k8s:
    #     hpaSpec:
    #       maxReplicas: 11
    #       minReplicas: 1
    # egressGateways:
    # - name: istio-egressgateway
    #   enabled: true