apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: istio-egressgateway
      istio: egressGateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istio-ingressgateway-api
  namespace: istio-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway-api
      istio: ingressgateway-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istiod
  namespace: istio-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: istiod
      istio: pilot