apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-web-app
  name: gin-web-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32426
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gin-web-app
  type: LoadBalancer